version: "3"

services:
  teamcity:
    image: jetbrains/teamcity-server
    restart: unless-stopped
    volumes:
      - ./teamcity_logs:/data/teamcity_server/datadir
      - ./teamcity_server_data:/opt/teamcity/logs
    ports:
      - "8111:8111"

  teamcity_agent:
    build: ./teamcity_agent
    restart: unless-stopped
    volumes:
      - ./teamcity_agent:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=teamcity:8111
